[package]
name                = "flo_draw"
version             = "0.2.0"
authors             = ["Andrew Hunter"]
license             = "Apache-2.0"
edition             = "2018"
readme              = "README.md"
repository          = "https://github.com/Logicalshift/flo_draw"
description         = "Quickly render 2D graphics to the screen"

[dependencies]
flo_canvas          = { path = "../canvas", version = "0.2" }
flo_stream          = "0.6"
flo_render          = { path = "../render", version = "0.2", features = [ "opengl" ] }
flo_render_canvas   = { path = "../render_canvas", version = "0.2"}
flo_binding         = { git = "https://github.com/Logicalshift/flo_binding", version = "2.0" }
desync              = "0.7"

glutin              = "0.26.0"
lazy_static         = "1.2"
futures             = "0.3"
gl                  = "0.14"

[dev-dependencies]
rand                = "0.8"
futures-timer       = "3.0"
