[package]
name                = "flo_draw"
version             = "0.2.1"
authors             = ["Andrew Hunter"]
license             = "Apache-2.0"
edition             = "2018"
readme              = "README.md"
repository          = "https://github.com/Logicalshift/flo_draw"
description         = "Quickly render 2D graphics to the screen"
categories          = [ "graphics", "rendering", "gui" ]

[dependencies]
flo_canvas          = "0.2"
flo_render          = { version = "0.2", features = [ "opengl" ] }
flo_render_canvas   = "0.2"
flo_stream          = "0.6"
flo_binding         = "2.0"
desync              = "0.7"

glutin              = "0.26.0"
lazy_static         = "1.2"
futures             = "0.3"
gl                  = "0.14"

[dev-dependencies]
rand                = "0.8"
futures-timer       = "3.0"
