[package]
name            = "flo_canvas"
version         = "0.3.0"
authors         = ["Andrew Hunter"]
license         = "Apache-2.0"
edition         = "2018"
readme          = "README.md"
categories      = [ "graphics", "rendering::data-formats" ]
repository      = "https://github.com/Logicalshift/flo_draw"
description     = "Library for describing graphics context drawing actions without requiring a specific implementation"

[features]
outline-fonts   = [ "allsorts", "flo_stream" ]

[dependencies]
flo_curves      = "0.4"
flo_stream      = { version = "0.6", optional = true }

futures         = "0.3"
desync          = "0.7"
rust-hsluv      = "0.1"
itertools       = "0.10"
serde           = { version = "1.0", features = [ "rc" ] }
serde_derive    = "1.0"
allsorts        = { version = "0.5", optional = true }
